language: node_js
node_js:
 - '8'

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.5.1
  - export PATH=$HOME/.yarn/bin:$PATH

script:
 - yarn lint
 - yarn flow
 - yarn test
 - bash example/test.sh
