// flow-typed signature: f36a50f75eb043ea014fca8a8a5579c7
// flow-typed version: <<STUB>>/private-package_v1.0.0/flow_v0.68.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'private-package'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'private-package' {
  declare module.exports: any
}
